# Generated by Django 5.2.5 on 2025-08-10 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="文章标题，最多200字符",
                        max_length=200,
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="文章正文内容，支持Markdown格式", verbose_name="内容"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="文章摘要，最多500字符，可为空",
                        max_length=500,
                        verbose_name="摘要",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="是否在前端显示此文章",
                        verbose_name="是否发布",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="链接名称")),
                (
                    "url",
                    models.URLField(
                        help_text="完整的URL地址，包含http://或https://",
                        verbose_name="链接地址",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="图标的CSS类名或图标文件名",
                        max_length=50,
                        verbose_name="图标名称",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("social", "社交媒体"),
                            ("tool", "工具网站"),
                            ("ai", "AI聊天"),
                            ("contact", "联系方式"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="链接分类",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="链接的简短描述",
                        max_length=200,
                        verbose_name="描述",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="数字越小越靠前显示",
                        verbose_name="显示顺序",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "链接",
                "verbose_name_plural": "链接",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="个人简介，最多1000字符",
                        max_length=1000,
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(
                        blank=True,
                        help_text="头像图片的URL地址",
                        verbose_name="头像URL",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="邮箱地址"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="所在地"),
                ),
                ("website", models.URLField(blank=True, verbose_name="个人网站")),
                (
                    "github_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="GitHub用户名"
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="技能标签，用逗号分隔，如：Python,Django,JavaScript",
                        verbose_name="技能标签",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人信息",
                "verbose_name_plural": "个人信息",
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="我的个人博客", max_length=200, verbose_name="网站标题"
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        help_text="网站的SEO描述",
                        max_length=500,
                        verbose_name="网站描述",
                    ),
                ),
                (
                    "site_keywords",
                    models.CharField(
                        blank=True,
                        help_text="SEO关键词，用逗号分隔",
                        max_length=200,
                        verbose_name="网站关键词",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="页脚文本"
                    ),
                ),
                (
                    "analytics_code",
                    models.TextField(
                        blank=True,
                        help_text="Google Analytics或其他统计工具的代码",
                        verbose_name="统计代码",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "网站配置",
                "verbose_name_plural": "网站配置",
            },
        ),
    ]
